/**
 * Created by hebo on 2017/6/25.
 */

pizzaElementGenerator(10);

function pizzaElementGenerator(len) {
  let makeRandomPizza = pizzaIngredientsGenerator().makeRandomPizza;
  // let docFragment = document.createDocumentFragment();
  let r = []
  for (let i = 2; i < len; i++) {
    let piz = makeRandomPizza();
    // docFragment.push(elements(`piz-${i}`, piz));
    r.push(i)
  }
  // console.log(docFragment.length)
  console.log(r.length)
  return;
  return docFragment;
  function elements(id, info) {
    let style = `width: 33.33%;height:325px;`;
    let ulChildren = function () {
      let result = [];
      return info.Ingredients.map(k => {
        return `<li>${k}</li>`
      })
    };
    let elem = document.createElement('div');
    elem.classList.add('randomPizzaContainer');
    elem.style.width = '33.33%';
    elem.style.height = '325px';
    elem.id = id;
    let childStr = ` <img src="images/pizza.png" class="img-responsive">
      <div class="" style="65%">
        <h4>${info.name}</h4>
        <ul>
        ${ulChildren()}
        </ul>
      </div>`
    elem.innerHTML = childStr;
    return elem;
  }
}


function pizzaIngredientsGenerator() {
  // 你可能已经发现了，这个网站会随机地生成披萨。
  // 下面的数组是所有可能组成披萨的原料。
  let pizzaIngredients = {};
  pizzaIngredients.meats = [
    'Pepperoni',
    'Sausage',
    'Fennel Sausage',
    'Spicy Sausage',
    'Chicken',
    'BBQ Chicken',
    'Chorizo',
    'Chicken Andouille',
    'Salami',
    'Tofu',
    'Bacon',
    'Canadian Bacon',
    'Proscuitto',
    'Italian Sausage',
    'Ground Beef',
    'Anchovies',
    'Turkey',
    'Ham',
    'Venison',
    'Lamb',
    'Duck',
    'Soylent Green',
    'Carne Asada',
    'Soppressata Picante',
    'Coppa',
    'Pancetta',
    'Bresola',
    'Lox',
    'Guanciale',
    'Chili',
    'Beef Jerky',
    'Pastrami',
    'Kielbasa',
    'Scallops',
    'Filet Mignon',
  ];
  pizzaIngredients.nonMeats = [
    'White Onions',
    'Red Onions',
    'Sauteed Onions',
    'Green Peppers',
    'Red Peppers',
    'Banana Peppers',
    'Ghost Peppers',
    'Habanero Peppers',
    'Jalapeno Peppers',
    'Stuffed Peppers',
    'Spinach',
    'Tomatoes',
    'Pineapple',
    'Pear Slices',
    'Apple Slices',
    'Mushrooms',
    'Arugula',
    'Basil',
    'Fennel',
    'Rosemary',
    'Cilantro',
    'Avocado',
    'Guacamole',
    'Salsa',
    'Swiss Chard',
    'Kale',
    'Sun Dried Tomatoes',
    'Walnuts',
    'Artichoke',
    'Asparagus',
    'Caramelized Onions',
    'Mango',
    'Garlic',
    'Olives',
    'Cauliflower',
    'Polenta',
    'Fried Egg',
    'Zucchini',
    'Hummus',
  ];
  pizzaIngredients.cheeses = [
    'American Cheese',
    'Swiss Cheese',
    'Goat Cheese',
    'Mozzarella Cheese',
    'Parmesean Cheese',
    'Velveeta Cheese',
    'Gouda Cheese',
    'Muenster Cheese',
    'Applewood Cheese',
    'Asiago Cheese',
    'Bleu Cheese',
    'Boursin Cheese',
    'Brie Cheese',
    'Cheddar Cheese',
    'Chevre Cheese',
    'Haletti Cheese',
    'Jack Cheese',
    'Pepper Jack Cheese',
    'Gruyere Cheese',
    'Limberger Cheese',
    'Manchego Cheese',
    'Marscapone Cheese',
    'Pecorino Cheese',
    'Provolone Cheese',
    'Queso Cheese',
    'Roquefort Cheese',
    'Romano Cheese',
    'Ricotta Cheese',
    'Smoked Gouda',
  ];
  pizzaIngredients.sauces = [
    'Red Sauce',
    'Marinara',
    'BBQ Sauce',
    'No Sauce',
    'Hot Sauce',
  ];
  pizzaIngredients.crusts = [
    'White Crust',
    'Whole Wheat Crust',
    'Flatbread Crust',
    'Stuffed Crust',
  ];
  // 披萨名字形容词的种类
  let adjectives = [
    'dark',
    'color',
    'whimsical',
    'shiny',
    'noisy',
    'apocalyptic',
    'insulting',
    'praise',
    'scientific',
  ];
  // 披萨名字名词的种类
  let nouns = [
    'animals',
    'everyday',
    'fantasy',
    'gross',
    'horror',
    'jewelry',
    'places',
    'scifi',
  ];
  // 用生成器发出的随机数来从数组中取出形容词
  function getAdj(x) {
    switch (x) {
      case 'dark':
        let dark = [
          'dark',
          'morbid',
          'scary',
          'spooky',
          'gothic',
          'deviant',
          'creepy',
          'sadistic',
          'black',
          'dangerous',
          'dejected',
          'haunted',
          'morose',
          'tragic',
          'shattered',
          'broken',
          'sad',
          'melancholy',
          'somber',
          'dark',
          'gloomy',
          'homicidal',
          'murderous',
          'shady',
          'misty',
          'dusky',
          'ghostly',
          'shadowy',
          'demented',
          'cursed',
          'insane',
          'possessed',
          'grotesque',
          'obsessed',
        ];
        return dark;
      case 'color':
        let colors = [
          'blue',
          'green',
          'purple',
          'grey',
          'scarlet',
          'NeonGreen',
          'NeonBlue',
          'NeonPink',
          'HotPink',
          'pink',
          'black',
          'red',
          'maroon',
          'silver',
          'golden',
          'yellow',
          'orange',
          'mustard',
          'plum',
          'violet',
          'cerulean',
          'brown',
          'lavender',
          'violet',
          'magenta',
          'chestnut',
          'rosy',
          'copper',
          'crimson',
          'teal',
          'indigo',
          'navy',
          'azure',
          'periwinkle',
          'brassy',
          'verdigris',
          'veridian',
          'tan',
          'raspberry',
          'beige',
          'sandy',
          'ElectricBlue',
          'white',
          'champagne',
          'coral',
          'cyan',
        ];
        return colors;
      case 'whimsical':
        let whimsy = [
          'whimsical',
          'silly',
          'drunken',
          'goofy',
          'funny',
          'weird',
          'strange',
          'odd',
          'playful',
          'clever',
          'boastful',
          'breakdancing',
          'hilarious',
          'conceited',
          'happy',
          'comical',
          'curious',
          'peculiar',
          'quaint',
          'quirky',
          'fancy',
          'wayward',
          'fickle',
          'yawning',
          'sleepy',
          'cockeyed',
          'dizzy',
          'dancing',
          'absurd',
          'laughing',
          'hairy',
          'smiling',
          'perplexed',
          'baffled',
          'cockamamie',
          'vulgar',
          'hoodwinked',
          'brainwashed',
        ];
        return whimsy;
      case 'shiny':
        let shiny = [
          'sapphire',
          'opal',
          'silver',
          'gold',
          'platinum',
          'ruby',
          'emerald',
          'topaz',
          'diamond',
          'amethyst',
          'turquoise',
          'starlit',
          'moonlit',
          'bronze',
          'metal',
          'jade',
          'amber',
          'garnet',
          'obsidian',
          'onyx',
          'pearl',
          'copper',
          'sunlit',
          'brass',
          'brassy',
          'metallic',
        ];
        return shiny;
      case 'noisy':
        let noisy = [
          'untuned',
          'loud',
          'soft',
          'shrieking',
          'melodious',
          'musical',
          'operatic',
          'symphonic',
          'dancing',
          'lyrical',
          'harmonic',
          'orchestral',
          'noisy',
          'dissonant',
          'rhythmic',
          'hissing',
          'singing',
          'crooning',
          'shouting',
          'screaming',
          'wailing',
          'crying',
          'howling',
          'yelling',
          'hollering',
          'caterwauling',
          'bawling',
          'bellowing',
          'roaring',
          'squealing',
          'beeping',
          'knocking',
          'tapping',
          'rapping',
          'humming',
          'scatting',
          'whispered',
          'whispering',
          'rasping',
          'buzzing',
          'whirring',
          'whistling',
          'whistled',
        ];
        return noisy;
      case 'apocalyptic':
        let apocalyptic = [
          'nuclear',
          'apocalyptic',
          'desolate',
          'atomic',
          'zombie',
          'collapsed',
          'grim',
          'fallen',
          'collapsed',
          'cannibalistic',
          'radioactive',
          'toxic',
          'poisonous',
          'venomous',
          'disastrous',
          'grimy',
          'dirty',
          'undead',
          'bloodshot',
          'rusty',
          'glowing',
          'decaying',
          'rotten',
          'deadly',
          'plagued',
          'decimated',
          'rotting',
          'putrid',
          'decayed',
          'deserted',
          'acidic',
        ];
        return apocalyptic;
      case 'insulting':
        let insulting = [
          'stupid',
          'idiotic',
          'fat',
          'ugly',
          'hideous',
          'grotesque',
          'dull',
          'dumb',
          'lazy',
          'sluggish',
          'brainless',
          'slow',
          'gullible',
          'obtuse',
          'dense',
          'dim',
          'dazed',
          'ridiculous',
          'witless',
          'daft',
          'crazy',
          'vapid',
          'inane',
          'mundane',
          'hollow',
          'vacuous',
          'boring',
          'insipid',
          'tedious',
          'monotonous',
          'weird',
          'bizarre',
          'backward',
          'moronic',
          'ignorant',
          'scatterbrained',
          'forgetful',
          'careless',
          'lethargic',
          'insolent',
          'indolent',
          'loitering',
          'gross',
          'disgusting',
          'bland',
          'horrid',
          'unseemly',
          'revolting',
          'homely',
          'deformed',
          'disfigured',
          'offensive',
          'cowardly',
          'weak',
          'villainous',
          'fearful',
          'monstrous',
          'unattractive',
          'unpleasant',
          'nasty',
          'beastly',
          'snide',
          'horrible',
          'syncophantic',
          'unhelpful',
          'bootlicking',
        ];
        return insulting;
      case 'praise':
        let praise = [
          'beautiful',
          'intelligent',
          'smart',
          'genius',
          'ingenious',
          'gorgeous',
          'pretty',
          'witty',
          'angelic',
          'handsome',
          'graceful',
          'talented',
          'exquisite',
          'enchanting',
          'fascinating',
          'interesting',
          'divine',
          'alluring',
          'ravishing',
          'wonderful',
          'magnificient',
          'marvelous',
          'dazzling',
          'cute',
          'charming',
          'attractive',
          'nifty',
          'delightful',
          'superior',
          'amiable',
          'gentle',
          'heroic',
          'courageous',
          'valiant',
          'brave',
          'noble',
          'daring',
          'fearless',
          'gallant',
          'adventurous',
          'cool',
          'enthusiastic',
          'fierce',
          'awesome',
          'radical',
          'tubular',
          'fearsome',
          'majestic',
          'grand',
          'stunning',
        ];
        return praise;
      case 'scientific':
        let scientific = [
          'scientific',
          'technical',
          'digital',
          'programming',
          'calculating',
          'formulating',
          'cyberpunk',
          'mechanical',
          'technological',
          'innovative',
          'brainy',
          'chemical',
          'quantum',
          'astro',
          'space',
          'theoretical',
          'atomic',
          'electronic',
          'gaseous',
          'investigative',
          'solar',
          'extinct',
          'galactic',
        ];
        return scientific;
      default:
        let scientific_default = [
          'scientific',
          'technical',
          'digital',
          'programming',
          'calculating',
          'formulating',
          'cyberpunk',
          'mechanical',
          'technological',
          'innovative',
          'brainy',
          'chemical',
          'quantum',
          'astro',
          'space',
          'theoretical',
          'atomic',
          'electronic',
          'gaseous',
          'investigative',
          'solar',
          'extinct',
          'galactic',
        ];
        return scientific_default;
    }
  }

  // 用生成器发出的随机数来从数组中取出名词
  function getNoun(y) {
    switch (y) {
      case 'animals':
        let animals = [
          'flamingo',
          'hedgehog',
          'owl',
          'elephant',
          'pussycat',
          'alligator',
          'dachsund',
          'poodle',
          'beagle',
          'crocodile',
          'kangaroo',
          'wallaby',
          'woodpecker',
          'eagle',
          'falcon',
          'canary',
          'parrot',
          'parakeet',
          'hamster',
          'gerbil',
          'squirrel',
          'rat',
          'dove',
          'toucan',
          'raccoon',
          'vulture',
          'peacock',
          'goldfish',
          'rook',
          'koala',
          'skunk',
          'goat',
          'rooster',
          'fox',
          'porcupine',
          'llama',
          'grasshopper',
          'gorilla',
          'monkey',
          'seahorse',
          'wombat',
          'wolf',
          'giraffe',
          'badger',
          'lion',
          'mouse',
          'beetle',
          'cricket',
          'nightingale',
          'hawk',
          'trout',
          'squid',
          'octopus',
          'sloth',
          'snail',
          'locust',
          'baboon',
          'lemur',
          'meerkat',
          'oyster',
          'frog',
          'toad',
          'jellyfish',
          'butterfly',
          'caterpillar',
          'tiger',
          'hyena',
          'zebra',
          'snail',
          'pig',
          'weasel',
          'donkey',
          'penguin',
          'crane',
          'buzzard',
          'vulture',
          'rhino',
          'hippopotamus',
          'dolphin',
          'sparrow',
          'beaver',
          'moose',
          'minnow',
          'otter',
          'bat',
          'mongoose',
          'swan',
          'firefly',
          'platypus',
        ];
        return animals;
      case 'profession':
        let professions = [
          'doctor',
          'lawyer',
          'ninja',
          'writer',
          'samurai',
          'surgeon',
          'clerk',
          'artist',
          'actor',
          'engineer',
          'mechanic',
          'comedian',
          'fireman',
          'nurse',
          'RockStar',
          'musician',
          'carpenter',
          'plumber',
          'cashier',
          'electrician',
          'waiter',
          'president',
          'governor',
          'senator',
          'scientist',
          'programmer',
          'singer',
          'dancer',
          'director',
          'mayor',
          'merchant',
          'detective',
          'investigator',
          'navigator',
          'pilot',
          'priest',
          'cowboy',
          'stagehand',
          'soldier',
          'ambassador',
          'pirate',
          'miner',
          'police',
        ];
        return professions;
      case 'fantasy':
        let fantasy = [
          'centaur',
          'wizard',
          'gnome',
          'orc',
          'troll',
          'sword',
          'fairy',
          'pegasus',
          'halfling',
          'elf',
          'changeling',
          'ghost',
          'knight',
          'squire',
          'magician',
          'witch',
          'warlock',
          'unicorn',
          'dragon',
          'wyvern',
          'princess',
          'prince',
          'king',
          'queen',
          'jester',
          'tower',
          'castle',
          'kraken',
          'seamonster',
          'mermaid',
          'psychic',
          'seer',
          'oracle',
        ];
        return fantasy;
      case 'music':
        let music = [
          'violin',
          'flute',
          'bagpipe',
          'guitar',
          'symphony',
          'orchestra',
          'piano',
          'trombone',
          'tuba',
          'opera',
          'drums',
          'harpsichord',
          'harp',
          'harmonica',
          'accordion',
          'tenor',
          'soprano',
          'baritone',
          'cello',
          'viola',
          'piccolo',
          'ukelele',
          'woodwind',
          'saxophone',
          'bugle',
          'trumpet',
          'sousaphone',
          'cornet',
          'stradiletius',
          'marimbas',
          'bells',
          'timpani',
          'bongos',
          'clarinet',
          'recorder',
          'oboe',
          'conductor',
          'singer',
        ];
        return music;
      case 'horror':
        let horror = [
          'murderer',
          'chainsaw',
          'knife',
          'sword',
          'murder',
          'devil',
          'killer',
          'psycho',
          'ghost',
          'monster',
          'godzilla',
          'werewolf',
          'vampire',
          'demon',
          'graveyard',
          'zombie',
          'mummy',
          'curse',
          'death',
          'grave',
          'tomb',
          'beast',
          'nightmare',
          'frankenstein',
          'specter',
          'poltergeist',
          'wraith',
          'corpse',
          'scream',
          'massacre',
          'cannibal',
          'skull',
          'bones',
          'undertaker',
          'zombie',
          'creature',
          'mask',
          'psychopath',
          'fiend',
          'satanist',
          'moon',
          'fullMoon',
        ];
        return horror;
      case 'gross':
        let gross = [
          'slime',
          'bug',
          'roach',
          'fluid',
          'pus',
          'booger',
          'spit',
          'boil',
          'blister',
          'orifice',
          'secretion',
          'mucus',
          'phlegm',
          'centipede',
          'beetle',
          'fart',
          'snot',
          'crevice',
          'flatulence',
          'juice',
          'mold',
          'mildew',
          'germs',
          'discharge',
          'toilet',
          'udder',
          'odor',
          'substance',
          'fluid',
          'moisture',
          'garbage',
          'trash',
          'bug',
        ];
        return gross;
      case 'everyday':
        let everyday = [
          'mirror',
          'knife',
          'fork',
          'spork',
          'spoon',
          'tupperware',
          'minivan',
          'suburb',
          'lamp',
          'desk',
          'stereo',
          'television',
          'TV',
          'book',
          'car',
          'truck',
          'soda',
          'door',
          'video',
          'game',
          'computer',
          'calender',
          'tree',
          'plant',
          'flower',
          'chimney',
          'attic',
          'kitchen',
          'garden',
          'school',
          'wallet',
          'bottle',
        ];
        return everyday;
      case 'jewelry':
        let jewelry = [
          'earrings',
          'ring',
          'necklace',
          'pendant',
          'choker',
          'brooch',
          'bracelet',
          'cameo',
          'charm',
          'bauble',
          'trinket',
          'jewelry',
          'anklet',
          'bangle',
          'locket',
          'finery',
          'crown',
          'tiara',
          'blingBling',
          'chain',
          'rosary',
          'jewel',
          'gemstone',
          'beads',
          'armband',
          'pin',
          'costume',
          'ornament',
          'treasure',
        ];
        return jewelry;
      case 'places':
        let places = [
          'swamp',
          'graveyard',
          'cemetery',
          'park',
          'building',
          'house',
          'river',
          'ocean',
          'sea',
          'field',
          'forest',
          'woods',
          'neighborhood',
          'city',
          'town',
          'suburb',
          'country',
          'meadow',
          'cliffs',
          'lake',
          'stream',
          'creek',
          'school',
          'college',
          'university',
          'library',
          'bakery',
          'shop',
          'store',
          'theater',
          'garden',
          'canyon',
          'highway',
          'restaurant',
          'cafe',
          'diner',
          'street',
          'road',
          'freeway',
          'alley',
        ];
        return places;
      case 'scifi':
        let scifi = [
          'robot',
          'alien',
          'raygun',
          'spaceship',
          'UFO',
          'rocket',
          'phaser',
          'astronaut',
          'spaceman',
          'planet',
          'star',
          'galaxy',
          'computer',
          'future',
          'timeMachine',
          'wormHole',
          'timeTraveler',
          'scientist',
          'invention',
          'martian',
          'pluto',
          'jupiter',
          'saturn',
          'mars',
          'quasar',
          'blackHole',
          'warpDrive',
          'laser',
          'orbit',
          'gears',
          'molecule',
          'electron',
          'neutrino',
          'proton',
          'experiment',
          'photon',
          'apparatus',
          'universe',
          'gravity',
          'darkMatter',
          'constellation',
          'circuit',
          'asteroid',
        ];
        return scifi;
      default:
        let scifi_default = [
          'robot',
          'alien',
          'raygun',
          'spaceship',
          'UFO',
          'rocket',
          'phaser',
          'astronaut',
          'spaceman',
          'planet',
          'star',
          'galaxy',
          'computer',
          'future',
          'timeMachine',
          'wormHole',
          'timeTraveler',
          'scientist',
          'invention',
          'martian',
          'pluto',
          'jupiter',
          'saturn',
          'mars',
          'quasar',
          'blackHole',
          'warpDrive',
          'laser',
          'orbit',
          'gears',
          'molecule',
          'electron',
          'neutrino',
          'proton',
          'experiment',
          'photon',
          'apparatus',
          'universe',
          'gravity',
          'darkMatter',
          'constellation',
          'circuit',
          'asteroid',
        ];
        return scifi_default;
    }
  }

  function makeRandomName() {
    let randomNumberAdj = parseInt(Math.random() * adjectives.length);
    let randomNumberNoun = parseInt(Math.random() * nouns.length);
    let adj = getAdj(randomNumberAdj);
    let nonu = getNoun(randomNumberNoun);
    let randomAdjective = parseInt(Math.random() * adjectives.length);
    let randomNoun = parseInt(Math.random() * nouns.length);
    let name =
      'The ' +
      capitalize(adj[randomAdjective]) +
      ' ' +
      capitalize(nonu[randomNoun]);
    return name;
  }


  function makeIngredients() {
    let result = [];
    let numberOfMeats = getRandomNumber(4);
    let numberOfNonMeats = getRandomNumber(3);
    let numberOfCheeses = getRandomNumber(2);
    let meatsLen = pizzaIngredients.meats.length;
    let nonMeatssLen = pizzaIngredients.nonMeats.length;
    let cheesesLen = pizzaIngredients.cheeses.length;
    let saucesLen = pizzaIngredients.sauces.length;
    let crustsLen = pizzaIngredients.crusts.length;

    for (let i = 0; i < numberOfMeats; i++) {
      result.push(pizzaIngredients.meats[getRandomNumber(meatsLen)])
    }

    for (let j = 0; j < numberOfNonMeats; j++) {
      result.push(pizzaIngredients.nonMeats[getRandomNumber(nonMeatssLen)])
    }

    for (let k = 0; k < numberOfCheeses; k++) {
      result.push(pizzaIngredients.cheeses[getRandomNumber(cheesesLen)])
    }

    result.push(pizzaIngredients.sauces[getRandomNumber(saucesLen)]);
    result.push(pizzaIngredients.crusts[getRandomNumber(crustsLen)]);
    return result;
  }

  function capitalize(s) {
    return s.charAt(0).toUpperCase() + s.slice(1);
  }

  function getRandomNumber(n) {
    return Math.floor(Math.random() * n);
  }

  return {
    makeRandomPizza: function () {
      return {
        name: makeRandomName(),
        Ingredients: makeIngredients()
      }
    },
    makeRandomName: makeRandomName
  }
}

function pizzaMoverGenerator() {
  let cols = 8;
  let s = 256;
  let docFragment = document.createDocumentFragment();
  for (let i = 0; i < 200; i++) {
    let elem = document.createElement('img');
    elem.className = 'mover';
    elem.src = 'images/pizza.png';
    elem.style.height = '100px';
    elem.style.width = '73.333px';
    elem.basicLeft = i % cols * s;
    elem.style.top = Math.floor(i / cols) * s + 'px';
    docFragment.appendChild(elem);
  }
  return docFragment;
}

